### ISSUE TITLE
After VHDX->RAW conversion missing partition table

### ISSUE THREAD

**Issue by tomcsanyid** [cloudbase/qemu#2]
I've been trying out the latest version of qemu-img (2.3.0) together with windows-openstack-imaging-tools and I think I found a bug: when converting from VHDX to RAW qemu-img seems to be missing the partition table completely. This results in a RAW image file that isn't understood by any Linux tool which were perfectly capable of reading previously generated files (which were converted from VHD if I remember correctly).
Checking the VHDX file itself I can see the partition layout in `diskpart` so I think the original file is okay.

However when trying to read the IMG file after the conversion:

```
# file hyperV-2012-updated-maas-puppet.img 
hyperV-2012-updated-maas-puppet.img: data

# fdisk hyperV-2012-updated-maas-puppet.img 

Welcome to fdisk (util-linux 2.26.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
```

I'd like to help any way I can to have this fixed, maybe I should try to create a test VHDX containing only the partition table and nothing else and see if I can reproduce the issue? Would that be helpful?

Thank you.
Domi

**Comment by tomcsanyid** [comment]
I did some testing, but I can't figure out what's going wrong. I created two test VHDX files one with MBR and one with GPT then I converted both of them to RAW. I checked them with `file` and `fdisk` and both of them showed results that are right:

```
# fdisk -l test_raw.img
Disk test_raw.img: 50 MiB, 52428800 bytes, 102400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7b3beb49

Device        Boot Start    End Sectors Size Id Type
test_raw.img1 *      128 100351  100224  49M  7 HPFS/NTFS/exFAT

# file test_raw.img 
test_raw.img: DOS/MBR boot sector MS-MBR Windows 7 english at offset 0x163 "Invalid partition table" at offset 0x17b "Error loading operating system" at offset 0x19a "Missing operating system", disk signature 0x7b3beb49; partition 1 : ID=0x7, active, start-CHS (0x0,2,3), end-CHS (0x5,254,63), startsector 128, 100224 sectors
```

I have followed all the steps that windows-openstack-imaging-tools do, converted the image, but the result is still OK. I don't think that the compression of the raw image causes data loss, but I'll keep investigating.

**Comment by petrutlucian94** [comment]
Hi Domi,

I've tried to reproduce this issue but the images were converted properly. Could you please paste the output of qemu-img info for both images? This may give us some hints on what went wrong.

Thanks,
Lucian

**Comment by tomcsanyid** [comment]
I wasn't able to reproduce the issue ever since, sorry for bothering you with it.
